export const ADD_UNIT = 'ADD_UNIT';
export const GET_UNITS = 'GET_UNITS';
export const DELETE_UNIT = 'DELETE_UNIT';

export const ADD_EMPLOYEE = 'ADD_EMPLOYEE';
export const GET_EMPLOYEES = 'GET_EMPLOYEES';
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';

export const ADD_MANUFACTURER = 'ADD_MANUFACTURER';
export const GET_MANUFACTURERS = 'GET_MANUFACTURERS';
export const DELETE_MANUFACTURER = 'DELETE_MANUFACTURER';

export const ADD_ITEM = 'ADD_ITEM';
export const GET_ITEMS =  'GET_ITEMS';
export const DELETE_ITEM =  'DELETE_ITEMS';
