export const ADD_UNIT = 'ADD_UNIT';
export const GET_UNITS = 'GET_UNITS';
export const DELETE_UNIT = 'DELETE_UNIT';

export const ADD_EMPLOYEE = 'ADD_EMPLOYEE';
export const GET_EMPLOYEES = 'GET_EMPLOYEES';
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';

export const ADD_MANUFACTURER = 'ADD_MANUFACTURER';
export const GET_MANUFACTURERS = 'GET_MANUFACTURERS';
export const DELETE_MANUFACTURER = 'DELETE_MANUFACTURER';

export const ADD_ITEM = 'ADD_ITEM';
export const GET_ITEMS =  'GET_ITEMS';
export const DELETE_ITEM =  'DELETE_ITEM';

export const ADD_ITEM_INSTANCE = 'ADD_ITEM_INSTANCE';
export const GET_ITEM_INSTANCES =  'GET_ITEM_INSTANCES';
export const DELETE_ITEM_INSTANCE =  'DELETE_ITEM_INSTANCE';

export const ADD_EMPLOYEE_ENTRY = 'ADD_EMPLOYEE_ENTRY';
export const GET_EMPLOYEE_ENTRIES = 'GET_EMPLOYEE_ENTRIES';
export const DELETE_EMPLOYEE_ENTRY = 'DELETE_EMPLOYEE_ENTRY';

export const ADD_TRANSPORT_ENTRY = 'ADD_TRANSPORT_ENTRY';
export const GET_TRANSPORT_ENTRIES = 'GET_TRANSPORT_ENTRIES';
export const DELETE_TRANSPORT_ENTRY = 'DELETE_TRANSPORT_ENTRY';

export const ADD_EQUIPMENT = 'ADD_EQUIPMENT';
export const GET_EQUIPMENT = 'GET_EQUIPMENT';
export const DELETE_EQUIPMENT = 'DELETE_EQUIPMENT';
